//
//  FruitProtocols.swift
//  Viper Todo List
//
//  Created MTMAC16 on 09/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FruitWireframeProtocol: BaseWireframeProtocol {

}
//MARK: Presenter -
protocol FruitPresenterProtocol: BasePresenterProtocol {

    var interactor: FruitInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol FruitInteractorOutputProtocol: BaseInteractorOutputProtocol {

    /* Interactor -> Presenter */
}

protocol FruitInteractorInputProtocol: BaseInteractorInputProtocol {

    var presenter: FruitInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol FruitViewProtocol: BaseViewProtocol {

    var presenter: FruitPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func showFruits(fruits: [Fruit])
    
}
