//
//  FruitPresenter.swift
//  Viper Todo List
//
//  Created MTMAC16 on 09/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FruitPresenter: FruitPresenterProtocol, FruitInteractorOutputProtocol {
    weak private var view: FruitViewProtocol?
    var interactor: FruitInteractorInputProtocol?
    private let router: FruitWireframeProtocol

    init(interface: FruitViewProtocol, interactor: FruitInteractorInputProtocol?, router: FruitWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func onError(with message: String) {
        view?.showError(message: message)
    }

}
