//
//  FruitInteractor.swift
//  Viper Todo List
//
//  Created MTMAC16 on 09/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FruitInteractor: FruitInteractorInputProtocol {

    weak var presenter: FruitInteractorOutputProtocol?
}
