//
//  FruitListViewController.swift
//  Viper Todo List
//
//  Created MTMAC16 on 10/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FruitListViewController: UIViewController, FruitListViewProtocol {
	var presenter: FruitListPresenterProtocol?
    var fruitList: [Fruit] = []

    @IBOutlet var tableViewFruit: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupTableViewFruit()
        presenter?.getFruitList()
    }
    
    private func setupTableViewFruit() {
        tableViewFruit.delegate = self
        tableViewFruit.dataSource = self
        tableViewFruit.tableFooterView = UIView()
        
        // MARK: cell registration
        tableViewFruit.register(UINib(nibName: "FruitCell", bundle: Bundle.main), forCellReuseIdentifier: "FruitCell")
    }
    
    func showFruitList(with fruits: [Fruit]) {
        fruitList.append(contentsOf: fruits)
        tableViewFruit.reloadData()
    }
    
    func showLoading() {
        HUDHelper.showLoading()
    }
    
    func showError(message: String) {
        HUDHelper.showError(message: message)
    }
    
    func dismissLoading() {
        HUDHelper.hide()
    }
}

extension FruitListViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 90.0
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return fruitList.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let fruit = fruitList[indexPath.row]
        let cell = tableView.dequeueReusableCell(withIdentifier: "FruitCell", for: indexPath) as! FruitCell
        cell.bindDataToView(fruit: fruit)
        
        return cell
    }
}

extension FruitListViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let fruit = fruitList[indexPath.row]
        presenter?.showFruitDetail(for: fruit)
    }
}
