//
//  FruitListInteractor.swift
//  Viper Todo List
//
//  Created MTMAC16 on 10/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FruitListInteractor: FruitListInteractorInputProtocol {
    weak var presenter: FruitListInteractorOutputProtocol?
    
    func getFruitList() {
        // simulate if the data is from the api
        LocalDataManger.shared.getFruitList { (fruitList) in
            self.presenter?.successGetFruitList(with: fruitList)
        }
    }
}
