//
//  FruitListRouter.swift
//  Viper Todo List
//
//  Created MTMAC16 on 10/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FruitListRouter: FruitListWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FruitListViewController(nibName: nil, bundle: nil)
        let interactor = FruitListInteractor()
        let router = FruitListRouter()
        let presenter = FruitListPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func showFruitDetail(with fruit: Fruit, from viewController: FruitListViewProtocol) {
        let fruitVC = FruitRouter.createModule(with: fruit)
        if let sourceView = viewController as? UIViewController {
            sourceView.navigationController?.pushViewController(fruitVC, animated: true)
        }
    }
}
