//
//  FruitListProtocols.swift
//  Viper Todo List
//
//  Created MTMAC16 on 10/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FruitListWireframeProtocol: BaseWireframeProtocol {
    func showFruitDetail(with fruit: Fruit, from viewController: FruitListViewProtocol)
}
//MARK: Presenter -
protocol FruitListPresenterProtocol: BasePresenterProtocol {

    var interactor: FruitListInteractorInputProtocol? { get set }
    
    /* View -> Presenter */
    func getFruitList()
    func showFruitDetail(for fruit: Fruit)
}

//MARK: Interactor -
protocol FruitListInteractorOutputProtocol: BaseInteractorOutputProtocol {

    /* Interactor -> Presenter */
    func successGetFruitList(with fruits: [Fruit])
}

protocol FruitListInteractorInputProtocol: BaseInteractorInputProtocol {

    var presenter: FruitListInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getFruitList()
}

//MARK: View -
protocol FruitListViewProtocol: BaseViewProtocol
{

    var presenter: FruitListPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func showFruitList(with fruits: [Fruit])
}
